# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.IntegerField(choices=[(1, 'paper book'), (2, 'ebook'), (3, 'audiobook')]),
        ),
    ]
