# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20170404_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=None),
        ),
    ]
