# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20170404_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.IntegerField(choices=[(1, 'crime'), (2, 'fantasy'), (3, 'sci-fi'), (4, 'romance'), (5, 'popular science'), (6, 'thriller'), (7, 'adventure'), (8, 'for children'), (9, 'poem'), (10, 'religion'), (11, 'travel')]),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.IntegerField(choices=[(1, 'paper book'), (2, 'ebook'), (3, 'audiobook')]),
        ),
    ]
