# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20170405_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.IntegerField(choices=[(1, 'crime'), (2, 'fantasy'), (3, 'sci-fi'), (4, 'romance'), (5, 'popular science'), (6, 'thriller'), (7, 'adventure'), (8, 'for children'), (9, 'poem'), (10, 'religion'), (11, 'travel')], default=1),
        ),
        migrations.RemoveField(
            model_name='book',
            name='type',
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.IntegerField(choices=[(1, 'paper book'), (2, 'ebook'), (3, 'audiobook')], default=1),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
