# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20170405_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='lat_name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='reader',
            old_name='first_name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='reader',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
    ]
