# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20170406_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
